apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: tetish-inn-ingress
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /

spec:
  rules:
  - http:
      paths:
      - pathType: Prefix
        path: "/"
        backend:
          service:
            name: tetish-inn-backend
            port: 
              number: 3000

